routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// route login
Route::get('/', 'LoginController@index')->name('login');
Route::post('/', 'LoginController@validasi')->name('validasi');
Route::get('/logout', 'LoginController@logout');
Route::get('/daftar', 'LoginController@daftar');
Route::post('/proses_daftar', 'LoginController@proses_daftar');

Route::group(['middleware' => ['auth']], function(){

	// route home
	Route::get('/home', 'HomeController@index');

	// route kategori
	Route::resource('/kategori', 'KategoriController')->except(['create']);
	Route::get('/table/kategori', 'KategoriController@dataTable')->name('table.kategori');
	Route::post('/kategori/tambah', 'KategoriController@store');
	Route::post('/kategori/{id}/update', 'KategoriController@update')->name('kategori/update');
	Route::get('/kategori/{id}/hapus', 'KategoriController@hapus')->name('kategori.hapus');

	// route produk
	Route::resource('/produk', 'ProdukController')->except([
		'create'
	]);
	Route::get('/table/produk', 'ProdukController@getJoin')->name('table.produk');
	Route::post('/produk/{id}/update', 'ProdukController@update')->name('produk/update');


	// route transaksi
	Route::get('/transaksi', 'TransaksiController@index')->name('transaksi');
	Route::get('/transaksi/pilih', 'TransaksiController@pilih_produk');
	Route::get('/transaksi/{id}/tambah', 'TransaksiController@tambah')->name('transaksi.tambah');
	Route::post('/transaksi/simpan', 'TransaksiController@simpan_transaksi');
	Route::get('/transaksi/{id}/detail', 'TransaksiController@detail_transaksi')->name('transaksi.detail');
	Route::get('/table/transaksi', 'TransaksiController@getJoin')->name('table.transaksi');
	Route::get('/table/pilih', 'TransaksiController@dataTable')->name('table.pilih');
});

app/Produk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    protected $table = 'produk';

    protected $fillable = ['nama', 'deskripsi', 'harga', 'stok', 'kategori_id'];

    public function kategori()
    {
    	return $this->belongsTo(Kategori::class);
    }

     public function transaksi()
    {
    	return $this->hasMany(Transaksi::class);
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use App\Produk;
use App\Kategori;
use DataTables;
use Illuminate\Http\Request;

class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kategori = Kategori::all();
        return view('pages/produk/index', ['kategori' => $kategori]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = Produk::create($request->all());
       
        return redirect('/produk')->with('berhasil', 'Data berhasil di simpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Produk::find($id);
        $kategori = Kategori::all();
        return view('pages/produk/edit', ['produk' => $data, 'kategori' => $kategori]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Produk::find($id);

        $data->update($request->all());

        return redirect('/produk')->with('berhasil', 'Data berhasil di simpan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Produk::find($id);

        $data->delete();
    }

    

    public function getJoin()
    {
        
        $data = Produk::join('kategori', 'produk.kategori_id', '=', 'kategori.id')->select(['produk.id', 'produk.nama', 'kategori.nama_kategori', 'produk.harga', 'produk.stok', 'produk.deskripsi']);

        return DataTables::of($data)
            ->addColumn('aksi', function($data){
                return view('layouts/includes/_action', [
                    'data' => $data,
                    'url_edit' => route('produk.edit', $data->id),
                    'url_destroy' => route('produk.destroy', $data->id)

                ]);
            })
            ->addIndexColumn()
            ->rawColumns(['aksi'])
            ->make(true);
    }
}

resources/views/pages/produk/edit.blade.php
@extends('layouts/apps')


@section('content')
<div class="col-md-12">
	<section class="panel">
		<header class="panel-heading">
			<div class="panel-actions">
				<a href="#" class="fa fa-caret-down"></a>
				<a href="#" class="fa fa-times"></a>
			</div>

			<h2 class="panel-title">Edit Kategori {{$produk->nama}}</h2>
		</header>
		<form class="form-horizontal form-bordered" method="POST" action="{{ route('produk/update', $produk->id) }}">
			@csrf
			<div class="panel-body">
				<div class="form-group">
					<label class="col-md-3 control-label" for="inputDefault">Nama Produk</label>
					<div class="col-md-6">
						<input type="text" class="form-control" id="inputDefault" name="nama" value="{{$produk->nama}}">
					</div>
				</div>			
			</div>
			<div class="panel-body">
				<div class="form-group">
					<label class="col-md-3 control-label">Kategori</label>
					<div class="col-md-6">
						<select class="form-control" name="kategori_id">
							@foreach($kategori as $category)
							<option value="{{$category->id}}" @if($produk->kategori_id == "$category->id") selected @endif>{{$category->nama_kategori}}</option>
							@endforeach
						</select>
					</div>
				</div>
			</div>
			<div class="panel-body">
				<div class="form-group">
					<label class="col-md-3 control-label" for="inputDefault">Harga Produk</label>
					<div class="col-md-6">
						<input type="text" class="form-control" id="inputDefault" name="harga" value="{{$produk->harga}}">
					</div>
				</div>			
			</div>
			<div class="panel-body">
				<div class="form-group">
					<label class="col-md-3 control-label" for="inputDefault">Stok Produk</label>
					<div class="col-md-6">
						<input type="text" class="form-control" id="inputDefault" name="stok" value="{{$produk->stok}}">
					</div>
				</div>			
			</div>
			<div class="panel-body">
				<div class="form-group">
					<label class="col-md-3 control-label" for="inputDefault">Deskripsi</label>
					<div class="col-md-6">
						<textarea class="form-control" rows="3" data-plugin-maxlength="" maxlength="140" name="deskripsi">{{$produk->deskripsi}}</textarea>
					</div>
				</div>			
			</div>
			<footer class="panel-footer">
				<div class="row">
					<div class="col-sm-9 col-sm-offset-3">
						<a href="{{ route('produk.index') }}" class="btn btn-default">Kembali</a>
						<button class="btn btn-warning">Update</button>
					</div>
				</div>
			</footer>
		</form>
	</section>
</div>

@stop

resources/views/pages/produk/index.blade.php
@extends('layouts/apps')

@section('content')

<div class="col-md-12">
	<section class="panel">
		<header class="panel-heading">
			@if(session('berhasil'))
				{{alertsukses()}}
			@endif	
			<div class="panel-actions">
				<a href="#" class="fa fa-caret-down"></a>
				<a href="#" title="Tambah Data" class="fa fa-plus modal-show" data-toggle="modal" data-target="#exampleModal"></a>
			</div>

			<h2 class="panel-title">Data Produk</h2>
		</header>
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-hover mb-none" id="datatable">
					<thead>
						<tr>
							<th>#</th>
							<th>Nama</th>
							<th>Kategori</th>
							<th>Harga</th>
							<th>Stok</th>
							<th>Deskripsi</th>
							<th>Aksi</th>
							
							
						</tr>
					</thead>
					<tbody>


					</tbody>
					<tfoot>
						<tr>
							<th>#</th>
							<th>Nama</th>
							<th>Kategori</th>
							<th>Harga</th>
							<th>Stok</th>
							<th>Deskripsi</th>
							<th>Aksi</th>
							
							
						</tr>
					</tfoot>

				</table>

			</div>
		</div>
	</section>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h5 class="modal-title" id="exampleModalLabel">Tambah Data Produk</h5>
			</div>
			<div class="modal-body">
				<div class="form-panel">
					<form class="form-horizontal style-form" method="POST" action="{{ route('produk.store') }}">
						@csrf
						<div class="form-group">
							<label class="col-md-3 control-label">Nama Produk</label>
							<div class="col-md-6">
								<input type="text" class="form-control input-rounded" name="nama" placeholder="Masukan Nama Produk" required="">
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-3 control-label">Kategori</label>
							<div class="col-md-6">
								<select class="form-control " name="kategori_id">
									@foreach($kategori as $category)
									<option value="{{$category->id}}">{{$category->nama_kategori}}</option>
									@endforeach
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-md-3 control-label">Harga</label>
							<div class="col-md-6">
								<input type="text" class="form-control input-rounded" name="harga" placeholder="Masukan Harga Produk" required="">
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-3 control-label">Stok</label>
							<div class="col-md-6">
								<input type="text" class="form-control input-rounded" name="stok" placeholder="Masukan Stok Produk" required="">
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-3 control-label" for="textareaDefault">Deskripsi Produk</label>
							<div class="col-md-6">
								<textarea class="form-control" rows="3" data-plugin-maxlength="" maxlength="140" name="deskripsi"></textarea>

							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
					<button type="submit" class="btn btn-primary">Simpan</button>
				</div>
			</form>
		</div>
	</div>
</div>

@stop
@push('scripts')

	<script >
		$('#datatable').DataTable({
			responsive: true,
			processing: true,
			serverSide: true,
			ajax: "{{ route('table.produk') }}",
			columns: [
				{ data: 'DT_RowIndex', name: 'produk.id' },
				{ data: 'nama', name: 'produk.nama' },
				{ data: 'nama_kategori', name: 'kategori.nama_kategori' },
				{ data: 'harga', name: 'produk.harga' },
				{ data: 'stok', name: 'produk.stok' },
				{ data: 'deskripsi', name: 'produk.deskripsi' },
				{ data: 'aksi', name: 'aksi' }

			]
		});
	</script>


@endpush