routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// route login
Route::get('/', 'LoginController@index')->name('login');
Route::post('/', 'LoginController@validasi')->name('validasi');
Route::get('/logout', 'LoginController@logout');
Route::get('/daftar', 'LoginController@daftar');
Route::post('/proses_daftar', 'LoginController@proses_daftar');

Route::group(['middleware' => ['auth']], function(){

	// route home
	Route::get('/home', 'HomeController@index');

	// route kategori
	Route::resource('/kategori', 'KategoriController')->except(['create']);
	Route::get('/table/kategori', 'KategoriController@dataTable')->name('table.kategori');
	Route::post('/kategori/tambah', 'KategoriController@store');
	Route::post('/kategori/{id}/update', 'KategoriController@update')->name('kategori/update');
	Route::get('/kategori/{id}/hapus', 'KategoriController@hapus')->name('kategori.hapus');

	// route produk
	Route::resource('/produk', 'ProdukController')->except([
		'create'
	]);
	Route::get('/table/produk', 'ProdukController@getJoin')->name('table.produk');
	Route::post('/produk/{id}/update', 'ProdukController@update')->name('produk/update');


	// route transaksi
	Route::get('/transaksi', 'TransaksiController@index')->name('transaksi');
	Route::get('/transaksi/pilih', 'TransaksiController@pilih_produk');
	Route::get('/transaksi/{id}/tambah', 'TransaksiController@tambah')->name('transaksi.tambah');
	Route::post('/transaksi/simpan', 'TransaksiController@simpan_transaksi');
	Route::get('/transaksi/{id}/detail', 'TransaksiController@detail_transaksi')->name('transaksi.detail');
	Route::get('/table/transaksi', 'TransaksiController@getJoin')->name('table.transaksi');
	Route::get('/table/pilih', 'TransaksiController@dataTable')->name('table.pilih');
});

resources/views/layouts/includes/_action.blade.php
<a href="{{ $url_edit }}" class="modal-show edit" title="Edit {{ $data->nama }}"><i class="fa fa-pencil"></i></a> | 
<a href="{{ $url_destroy }}" class="btn-delete" title="Hapus {{ $data->nama }}"><i class="fa fa-trash-o"></i></a>

resources/views/layouts/includes/_aksi.blade.php
<a href="{{ $url_detail }}" class="modal-show" title="Detail Transaksi"><i class="fa fa-eye"></i></a>

resources/views/layouts/includes/_navbar.blade.php
<div class="header-right">
	
	<form action="pages-search-results.html" class="search nav-form">
		<div class="input-group input-search">
			<input type="text" class="form-control" name="q" id="q" placeholder="Search...">
			<span class="input-group-btn">
				<button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
			</span>
		</div>
	</form>
	
	<span class="separator"></span>
	
	<ul class="notifications">
		<li>
			<a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
				<i class="fa fa-tasks"></i>
				<span class="badge">3</span>
			</a>
			
			<div class="dropdown-menu notification-menu large">
				<div class="notification-title">
					<span class="pull-right label label-default">3</span>
					Tasks
				</div>
				
				<div class="content">
					<ul>
						<li>
							<p class="clearfix mb-xs">
								<span class="message pull-left">Generating Sales Report</span>
								<span class="message pull-right text-dark">60%</span>
							</p>
							<div class="progress progress-xs light">
								<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
							</div>
						</li>
						
						<li>
							<p class="clearfix mb-xs">
								<span class="message pull-left">Importing Contacts</span>
								<span class="message pull-right text-dark">98%</span>
							</p>
							<div class="progress progress-xs light">
								<div class="progress-bar" role="progressbar" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100" style="width: 98%;"></div>
							</div>
						</li>
						
						<li>
							<p class="clearfix mb-xs">
								<span class="message pull-left">Uploading something big</span>
								<span class="message pull-right text-dark">33%</span>
							</p>
							<div class="progress progress-xs light mb-xs">
								<div class="progress-bar" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%;"></div>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</li>
		<li>
			<a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
				<i class="fa fa-envelope"></i>
				<span class="badge">4</span>
			</a>
			
			<div class="dropdown-menu notification-menu">
				<div class="notification-title">
					<span class="pull-right label label-default">230</span>
					Messages
				</div>
				
				<div class="content">
					<ul>
						<li>
							<a href="#" class="clearfix">
								<figure class="image">
									<img src="assets/images/!sample-user.jpg" alt="Joseph Doe Junior" class="img-circle" />
								</figure>
								<span class="title">Joseph Doe</span>
								<span class="message">Lorem ipsum dolor sit.</span>
							</a>
						</li>
						<li>
							<a href="#" class="clearfix">
								<figure class="image">
									<img src="assets/images/!sample-user.jpg" alt="Joseph Junior" class="img-circle" />
								</figure>
								<span class="title">Joseph Junior</span>
								<span class="message truncate">Truncated message. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet lacinia orci. Proin vestibulum eget risus non luctus. Nunc cursus lacinia lacinia. Nulla molestie malesuada est ac tincidunt. Quisque eget convallis diam, nec venenatis risus. Vestibulum blandit faucibus est et malesuada. Sed interdum cursus dui nec venenatis. Pellentesque non nisi lobortis, rutrum eros ut, convallis nisi. Sed tellus turpis, dignissim sit amet tristique quis, pretium id est. Sed aliquam diam diam, sit amet faucibus tellus ultricies eu. Aliquam lacinia nibh a metus bibendum, eu commodo eros commodo. Sed commodo molestie elit, a molestie lacus porttitor id. Donec facilisis varius sapien, ac fringilla velit porttitor et. Nam tincidunt gravida dui, sed pharetra odio pharetra nec. Duis consectetur venenatis pharetra. Vestibulum egestas nisi quis elementum elementum.</span>
							</a>
						</li>
						<li>
							<a href="#" class="clearfix">
								<figure class="image">
									<img src="assets/images/!sample-user.jpg" alt="Joe Junior" class="img-circle" />
								</figure>
								<span class="title">Joe Junior</span>
								<span class="message">Lorem ipsum dolor sit.</span>
							</a>
						</li>
						<li>
							<a href="#" class="clearfix">
								<figure class="image">
									<img src="assets/images/!sample-user.jpg" alt="Joseph Junior" class="img-circle" />
								</figure>
								<span class="title">Joseph Junior</span>
								<span class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet lacinia orci. Proin vestibulum eget risus non luctus. Nunc cursus lacinia lacinia. Nulla molestie malesuada est ac tincidunt. Quisque eget convallis diam.</span>
							</a>
						</li>
					</ul>
					
					<hr />
					
					<div class="text-right">
						<a href="#" class="view-more">View All</a>
					</div>
				</div>
			</div>
		</li>
		<li>
			<a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
				<i class="fa fa-bell"></i>
				<span class="badge">3</span>
			</a>
			
			<div class="dropdown-menu notification-menu">
				<div class="notification-title">
					<span class="pull-right label label-default">3</span>
					Alerts
				</div>
				
				<div class="content">
					<ul>
						<li>
							<a href="#" class="clearfix">
								<div class="image">
									<i class="fa fa-thumbs-down bg-danger"></i>
								</div>
								<span class="title">Server is Down!</span>
								<span class="message">Just now</span>
							</a>
						</li>
						<li>
							<a href="#" class="clearfix">
								<div class="image">
									<i class="fa fa-lock bg-warning"></i>
								</div>
								<span class="title">User Locked</span>
								<span class="message">15 minutes ago</span>
							</a>
						</li>
						<li>
							<a href="#" class="clearfix">
								<div class="image">
									<i class="fa fa-signal bg-success"></i>
								</div>
								<span class="title">Connection Restaured</span>
								<span class="message">10/10/2014</span>
							</a>
						</li>
					</ul>
					
					<hr />
					
					<div class="text-right">
						<a href="#" class="view-more">View All</a>
					</div>
				</div>
			</div>
		</li>
	</ul>
	
	<span class="separator"></span>
	
	<div id="userbox" class="userbox">
		<a href="#" data-toggle="dropdown">
			<figure class="profile-picture">
				<img src="assets/images/!logged-user.jpg" alt="Joseph Doe" class="img-circle" data-lock-picture="assets/images/!logged-user.jpg" />
			</figure>
			<div class="profile-info" data-lock-name="John Doe" data-lock-email="johndoe@JSOFT.com">
				<span class="name">{{ auth()->user()->name }}</span>
				<span class="role">{{ auth()->user()->level }}</span>
			</div>
			
			<i class="fa custom-caret"></i>
		</a>
		
		<div class="dropdown-menu">
			<ul class="list-unstyled">
				<li class="divider"></li>
				<li>
					<a role="menuitem" tabindex="-1" href="#"><i class="fa fa-user"></i> My Profile</a>
				</li>
				<li>
					<a role="menuitem" tabindex="-1" href="#" data-lock-screen="true"><i class="fa fa-lock"></i> Lock Screen</a>
				</li>
				<li>
					<a role="menuitem" tabindex="-1" href="/logout"><i class="fa fa-power-off"></i> Logout</a>
				</li>
			</ul>
		</div>
	</div>
</div>

resources/views/layouts/includes/_pilih.blade.php
<a href="{{ $url_pilih }}" class="btn btn-success sm" title="Pilih Produk {{ $data->nama }}">Pilih</a>

resources/views/layouts/includes/_sidebar.blade.php
<aside id="sidebar-left" class="sidebar-left">
				
					<div class="sidebar-header">
						<div class="sidebar-title">
							Navigation
						</div>
						<div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
							<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
						</div>
					</div>
				
					<div class="nano">
						<div class="nano-content">
							<nav id="menu" class="nav-main" role="navigation">
								<ul class="nav nav-main">
									<li class="nav-active">
										<a href="/home">
											<i class="fa fa-home" aria-hidden="true"></i>
											<span>Dashboard</span>
										</a>
									</li>
									
									<li class="nav-parent">
										<a>
											<i class="fa fa-database" aria-hidden="true"></i>
											<span>Master</span>
										</a>
										<ul class="nav nav-children">
											<li>
												<a href="{{ route('kategori.index') }}" class="fa fa-reorder">
													<span>Data Kategori Produk  </span>
														
												</a>
											</li>
											<li>
												<a href="{{ route('produk.index') }}" class="fa fa-tags">
													Data Produk
													 	
												</a>
											</li>
											

										</ul>
									</li>
									<li class="nav-active">
										<a href="{{ route('transaksi') }}">
											<i class="fa fa-shopping-cart" aria-hidden="true"></i>
											<span>Transaksi</span>
										</a>
									</li>
									<li class="nav-active">
										<a href="#">
											<i class="fa fa-credit-card" aria-hidden="true"></i>
											<span>Refund</span>
										</a>
									</li>
								</ul>
							</nav>
				
							<hr class="separator" />
				
							
				
							<hr class="separator" />
				
							
						</div>
				
					</div>
				
				</aside>